spring:
  application:
    name: activiti-module

  activiti:
    async-executor-activate: true
    mail-server-use-ssl: true
    #自动更新数据库
    database-schema-update: true
    #校验流程文件，默认校验resources下的processes文件夹里的流程文件
    check-process-definitions: false
    #restApiEnabled: false

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://111.231.193.138:3306/test?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: ZhongFei-ca-2018
    # Hikari数据源配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
