#
spring:
  application:
    name: resource-server-module

server:
  port: 8080

# 认证服务器配置
security:
  oauth2:
    client:
      client-id: sysclientid
      client-secret: syssecretid    #加密前的
      access-token-uri: http://localhost:8081/oauth/token
      user-authorization-uri: http://localhost:8081/oauth/authorize
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
#  basic:
#    enabled: false
