spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  application:
    name: layui-module
eureka:
  client:
    service-url:
          defaultZone: http://localhost:9090/eureka/
server:
  port: 9010
logging:
  level:
    web: DEBUG